@file:Suppress("unused")

package dev.alt236.codeplasteragetestapp.tricky.synthetics

class Comparator {
    data class DummyObject(
        val name: String,
    )

    /**
     * This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: class dev.alt236testapp.unrunables.KotlinInternalSynthetic$syntheticComparator$$inlined$sortedBy$1
     * java.lang.UnsupportedOperationException: This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: class dev.alt236testapp.unrunables.KotlinInternalSynthetic$syntheticComparator$$inlined$sortedBy$1
     *
     */
    @Suppress("UNUSED_VARIABLE")
    fun syntheticComparator() {
        val list: List<DummyObject> =
            listOf(
                DummyObject("Bob"),
                DummyObject("Alice"),
                DummyObject("Eve"),
            ).sortedBy { it.name }
    }
}
