@file:Suppress("unused")

package uk.co.alt236.codeplasteragetestapp.tricky.synthetics

class Inline {

    // TODO: Fix this test
//    /**
//     * This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: class uk.co.alt236.codeplasteragetestapp.unrunables.KotlinSynthetics$inlineSynthetic$1$2
//     * java.lang.UnsupportedOperationException: This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: class uk.co.alt236.codeplasteragetestapp.unrunables.KotlinSynthetics$inlineSynthetic$1$2
//     */
//    inline fun <reified T : Any> inlineSynthetic(): Call<T> =
//        mockk<Call<T>>().also { call ->
//            every { call.enqueue(any()) }.answers {
//                (arg(0) as Callback<T>).onResponse(call, mockk())
//            }
//        }
}
