@file:Suppress("unused")

package uk.co.alt236.codeplasteragetestapp.unrunables.synthetics

class Comparator {

    data class DummyObject(val name: String)

    /**
     * This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: class uk.co.alt236.codeplasteragetestapp.unrunables.KotlinInternalSynthetic$syntheticComparator$$inlined$sortedBy$1
     * java.lang.UnsupportedOperationException: This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: class uk.co.alt236.codeplasteragetestapp.unrunables.KotlinInternalSynthetic$syntheticComparator$$inlined$sortedBy$1
     *
     */
    @Suppress("UNUSED_VARIABLE")
    fun syntheticComparator() {
        val list: List<DummyObject> = listOf(
            DummyObject("Bob"),
            DummyObject("Alice"),
            DummyObject("Eve"),
        ).sortedBy { it.name }
    }

}